# Generated by Django 3.2.20 on 2023-09-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.IntegerField(choices=[(1, ' 10:00 am '), (2, ' 12:00 pm '), (3, ' 2:00pm '), (4, ' 4:00pm ')], default=1),
        ),
    ]
