# Generated by Django 3.2.20 on 2023-08-31 00:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_post_slug'),
    ]
